In [14]:
import pandas as pd

auswahl = pd.read_csv("../daten/annotations_auswahl.csv")
meine_gold = pd.read_csv("annotation_template.csv")
# Nur die IDs als Grundlage
meine_gold['id'] = auswahl[["refnr"]]
fabio_gold = meine_gold


fabio_gold

,id,homeoffice,vertragsart,erfahrungslevel,gehalt_min_eur,gehalt_zeitraum,skills_top3,notiz
0,15939-BB-633097-7878-9999-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15939-BB-633095-7878-7490-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15939-BB-633455-7878-6343-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15939-BB-633457-7878-2175-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18777-931781141-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,13999-k53401.30280-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,15939-BB-632493-7878-9058-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,13635-7fbe73ac_JB5131141-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20536-lutif851vc-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,12826-SA0136034_JB5125696-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,13509-00002110865001-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12862-244829-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# für Fabios Version anzeigen lassen
i = 8

print("ID:", auswahl.loc[i, "refnr"])
print("TITEL:", auswahl.loc[i, "titel"])
print("FIRMA:", auswahl.loc[i, "firma"])
print("TEXT:", auswahl.loc[i, "text"])
print("ORT:", auswahl.loc[i, "ort"])

ID: 20536-lutif851vc-S
TITEL: Research Associate / Wissenschaftliche*r Mitarbeiter*in at the In...
FIRMA: Technische Universität Hamburg
TEXT: Research Associate (m/f/d) -
Wissenschaftliche*r Mitarbeiter*in

# **Institute of[Innovation Marketing](https://www.tuhh.de/im/home)** **Remuneration**EG 13 [TV-L](https://t1p.de/wn3d9) **ID: 10726WW3 Start of employment:01.10.2026** **Application deadline** 20.05.2026 **Scope** full time and fixed term until 30.09.2029

Would you like to help ensure that scientific findings have a stronger impact on business and society? Are you interested in AI-based tools that connect research results and technological developments with applications? Would you like to explore these technology transfer topics as part of a PhD project within an international consortium?

This position involves working in a research project with partners from several countries to transfer scientific findings and technological developments into meaningful applications. A central focus is the use of AI-based tools that systematically link research with needs arising from business, industry, and society. In addition, the project promotes cross-institutional collaboration for technology transfer in order to make better use of the technological potential of universities.

This position offers the opportunity to pursue a doctoral thesis in an international research environment and to contribute to university teaching. The position will be based at the Institute of Innovation Marketing at TU Hamburg, where you will be part of a dynamic and interdisciplinary research team.

YOUR TASKS

- Work in an international research project on new approaches to knowledge and technology transfer from universities
- Support the privacy-compliant integration of university research and innovation data from different sources
- Contribute to the development and support the testing of AI-based tools that help translate research results into applications
- Present the results at international conferences and publish in academic journals
- Integrate research findings into university teaching

YOUR PROFILE

Requirements

- Completed university studies (master degree or equivalent), in particular in Business Administration, Industrial Engineering, Computer Science or Data Science (minimum grade of 2.5 according to German grading system)

# Desired knowledge and personal skills

- Very good written and spoken English
- Knowledge and Experience of Machine Learning and Artificial Intelligence
- Knowledge of empirical research methods and data analysis
- Experience of technology transfer
- Interest in interdisciplinary and international collaboration and in research-based academic teaching

# OUR OFFER

- Scientific qualification with the opportunity to pursue a PhD
- A job in an interesting, friendly and appreciative working environment
- Intensive induction/ onboarding
- Possibility of mobile working
- Flexible and family-friendly working conditions

# At the heart of TU Hamburg’s research, teaching and transfer of technology is the guiding principle of developing technology for people. The TU Hamburg sees itself in this context as a family-friendly and sustainable university with high performance and quality standards that strives for excellence in all its research fields. Interdisciplinarity, innovation, regionality and internationality are binding principles in our actions. With currently around 8.000 students, 110 professors and 1.650 employees, the TU Hamburg is characterised by short decision-making processes and close cooperation between the board, the institutes, the deans of studies, the research areas and the administration. We identify ourselves with a modern leadership culture and cultivate appreciative interaction.

# For further information please contact Anke Bohne, Tel.-Nr. +49 40 30601 4515, Email: [anke.bohne@tuhh.de].

We value diversity, therefore all applications are welcome, regardless of gender, gender identity, ethnic origin, nationality, age, religion and belief, disability, sexual orientation and identity or social background.

The TU Hamburg stands for [equal opportunities](https://www.tuhh.de/tuhh/tu-hamburg/struktur/personalrat-und-interessensvertretungen/gleichstellungsreferat) as well as [appreciative and respectful cooperation.](https://www.tuhh.de/gutes-miteinander/startseite/vereinbarung-miteinander)

Please send your complete application documents (cover letter, curriculum vitae in table form, proof of completed training and/or university degree, job references or certificates of employment) via the online application system.

[Notice for severely disabled persons and people with equal status.](https://www.hamburg.de/politik-und-verwaltung/behoerden/personalamt/arbeit-fuer-schwerbehinderte-118778)

**Notice for graduates of foreign educational qualifications:**
Please submit proof of all obtained university degrees and, if available, the recognition of your educational qualifications in Germany (e.g. anabin excerpts and/or acknowledgement of previous employers).
ORT: Hamburg

In [ ]:
# Fabios Annotationen erstellen


fabio_gold.loc[i, "homeoffice"] = "ja"
fabio_gold.loc[i, "vertragsart"] = "festanstellung"
fabio_gold.loc[i, "erfahrungslevel"] = "senior"
fabio_gold.loc[i, "gehalt_min_eur"] = "nicht_genannt"
fabio_gold.loc[i, "gehalt_zeitraum"] = "nicht_genannt"
fabio_gold.loc[i, "skills_top3"] = "Accounting/Controlling|MS Office|ERP-Systeme"
fabio_gold.loc[i, "notiz"] = "senior, da u.a. senior level "

fabio_gold

In [25]:
# für meine Version anzeigen lassen


for spalte in auswahl.columns:
    print("="*80)
    print(spalte.upper())
    print(auswahl.loc[i, spalte])

================================================================================
REFNR
20536-lutif851vc-S
================================================================================
TITEL
Research Associate / Wissenschaftliche*r Mitarbeiter*in at the In...
================================================================================
FIRMA
Technische Universität Hamburg
================================================================================
TEXT
Research Associate (m/f/d) -
Wissenschaftliche*r Mitarbeiter*in

# **Institute of[Innovation Marketing](https://www.tuhh.de/im/home)** **Remuneration**EG 13 [TV-L](https://t1p.de/wn3d9) **ID: 10726WW3 Start of employment:01.10.2026** **Application deadline** 20.05.2026 **Scope** full time and fixed term until 30.09.2029

Would you like to help ensure that scientific findings have a stronger impact on business and society? Are you interested in AI-based tools that connect research results and technological developments with applications? Would you like to explore these technology transfer topics as part of a PhD project within an international consortium?

This position involves working in a research project with partners from several countries to transfer scientific findings and technological developments into meaningful applications. A central focus is the use of AI-based tools that systematically link research with needs arising from business, industry, and society. In addition, the project promotes cross-institutional collaboration for technology transfer in order to make better use of the technological potential of universities.

This position offers the opportunity to pursue a doctoral thesis in an international research environment and to contribute to university teaching. The position will be based at the Institute of Innovation Marketing at TU Hamburg, where you will be part of a dynamic and interdisciplinary research team.

YOUR TASKS

- Work in an international research project on new approaches to knowledge and technology transfer from universities
- Support the privacy-compliant integration of university research and innovation data from different sources
- Contribute to the development and support the testing of AI-based tools that help translate research results into applications
- Present the results at international conferences and publish in academic journals
- Integrate research findings into university teaching

YOUR PROFILE

Requirements

- Completed university studies (master degree or equivalent), in particular in Business Administration, Industrial Engineering, Computer Science or Data Science (minimum grade of 2.5 according to German grading system)

# Desired knowledge and personal skills

- Very good written and spoken English
- Knowledge and Experience of Machine Learning and Artificial Intelligence
- Knowledge of empirical research methods and data analysis
- Experience of technology transfer
- Interest in interdisciplinary and international collaboration and in research-based academic teaching

# OUR OFFER

- Scientific qualification with the opportunity to pursue a PhD
- A job in an interesting, friendly and appreciative working environment
- Intensive induction/ onboarding
- Possibility of mobile working
- Flexible and family-friendly working conditions

# At the heart of TU Hamburg’s research, teaching and transfer of technology is the guiding principle of developing technology for people. The TU Hamburg sees itself in this context as a family-friendly and sustainable university with high performance and quality standards that strives for excellence in all its research fields. Interdisciplinarity, innovation, regionality and internationality are binding principles in our actions. With currently around 8.000 students, 110 professors and 1.650 employees, the TU Hamburg is characterised by short decision-making processes and close cooperation between the board, the institutes, the deans of studies, the research areas and the administration. We identify ourselves with a modern leadership culture and cultivate appreciative interaction.

# For further information please contact Anke Bohne, Tel.-Nr. +49 40 30601 4515, Email: [anke.bohne@tuhh.de].

We value diversity, therefore all applications are welcome, regardless of gender, gender identity, ethnic origin, nationality, age, religion and belief, disability, sexual orientation and identity or social background.

The TU Hamburg stands for [equal opportunities](https://www.tuhh.de/tuhh/tu-hamburg/struktur/personalrat-und-interessensvertretungen/gleichstellungsreferat) as well as [appreciative and respectful cooperation.](https://www.tuhh.de/gutes-miteinander/startseite/vereinbarung-miteinander)

Please send your complete application documents (cover letter, curriculum vitae in table form, proof of completed training and/or university degree, job references or certificates of employment) via the online application system.

[Notice for severely disabled persons and people with equal status.](https://www.hamburg.de/politik-und-verwaltung/behoerden/personalamt/arbeit-fuer-schwerbehinderte-118778)

**Notice for graduates of foreign educational qualifications:**
Please submit proof of all obtained university degrees and, if available, the recognition of your educational qualifications in Germany (e.g. anabin excerpts and/or acknowledgement of previous employers).
================================================================================
ORT
Hamburg
================================================================================
BERUF
Wissenschaftliche/r Mitarbeiter/in
================================================================================
VEROEFFENTLICHUNG
2026-04-27
================================================================================
HOMEOFFICE_API
False
================================================================================
GEHALT_API
KEINE_ANGABEN
================================================================================
VERTRAGSDAUER_API
BEFRISTET
================================================================================
RAW
{'stellenangebotsart': 'ARBEIT', 'stellenangebotsTitel': 'Research Associate / Wissenschaftliche*r Mitarbeiter*in at the In...', 'quereinstiegGeeignet': False, 'stellenangebotsBeschreibung': 'Research Associate (m/f/d) -   \nWissenschaftliche*r Mitarbeiter*in\n\n# **Institute of[Innovation Marketing](https://www.tuhh.de/im/home)** **Remuneration**EG 13 [TV-L](https://t1p.de/wn3d9) **ID: 10726WW3 Start of employment:01.10.2026** **Application deadline** 20.05.2026 **Scope** full time and fixed term until 30.09.2029\n\nWould you like to help ensure that scientific findings have a stronger impact on business and society? Are you interested in AI-based tools that connect research results and technological developments with applications? Would you like to explore these technology transfer topics as part of a PhD project within an international consortium?  \n\nThis position involves working in a research project with partners from several countries to transfer scientific findings and technological developments into meaningful applications. A central focus is the use of AI-based tools that systematically link research with needs arising from business, industry, and society. In addition, the project promotes cross-institutional collaboration for technology transfer in order to make better use of the technological potential of universities.  \n\nThis position offers the opportunity to pursue a doctoral thesis in an international research environment and to contribute to university teaching. The position will be based at the Institute of Innovation Marketing at TU Hamburg, where you will be part of a dynamic and interdisciplinary research team.\n\nYOUR TASKS\n\n- Work in an international research project on new approaches to knowledge and technology transfer from universities\n- Support the privacy-compliant integration of university research and innovation data from different sources\n- Contribute to the development and support the testing of AI-based tools that help translate research results into applications\n- Present the results at international conferences and publish in academic journals\n- Integrate research findings into university teaching\n\nYOUR PROFILE\n\nRequirements\n\n- Completed university studies (master degree or equivalent), in particular in Business Administration, Industrial Engineering, Computer Science or Data Science (minimum grade of 2.5 according to German grading system)\n\n# Desired knowledge and personal skills\n\n- Very good written and spoken English\n- Knowledge and Experience of Machine Learning and Artificial Intelligence\n- Knowledge of empirical research methods and data analysis\n- Experience of technology transfer\n- Interest in interdisciplinary and international collaboration and in research-based academic teaching\n\n# OUR OFFER\n\n- Scientific qualification with the opportunity to pursue a PhD\n- A job in an interesting, friendly and appreciative working environment\n- Intensive induction/ onboarding\n- Possibility of mobile working\n- Flexible and family-friendly working conditions\n\n# At the heart of TU Hamburg’s research, teaching and transfer of technology is the guiding principle of developing technology for people. The TU Hamburg sees itself in this context as a family-friendly and sustainable university with high performance and quality standards that strives for excellence in all its research fields. Interdisciplinarity, innovation, regionality and internationality are binding principles in our actions. With currently around 8.000 students, 110 professors and 1.650 employees, the TU Hamburg is characterised by short decision-making processes and close cooperation between the board, the institutes, the deans of studies, the research areas and the administration. We identify ourselves with a modern leadership culture and cultivate appreciative interaction.\n\n# For further information please contact Anke Bohne, Tel.-Nr. +49 40 30601 4515, Email: [anke.bohne@tuhh.de].\n\nWe value diversity, therefore all applications are welcome, regardless of gender, gender identity, ethnic origin, nationality, age, religion and belief, disability, sexual orientation and identity or social background.  \n\nThe TU Hamburg stands for [equal opportunities](https://www.tuhh.de/tuhh/tu-hamburg/struktur/personalrat-und-interessensvertretungen/gleichstellungsreferat) as well as [appreciative and respectful cooperation.](https://www.tuhh.de/gutes-miteinander/startseite/vereinbarung-miteinander)  \n\nPlease send your complete application documents (cover letter, curriculum vitae in table form, proof of completed training and/or university degree, job references or certificates of employment) via the online application system.  \n\n[Notice for severely disabled persons and people with equal status.](https://www.hamburg.de/politik-und-verwaltung/behoerden/personalamt/arbeit-fuer-schwerbehinderte-118778)  \n\n**Notice for graduates of foreign educational qualifications:**  \nPlease submit proof of all obtained university degrees and, if available, the recognition of your educational qualifications in Germany (e.g. anabin excerpts and/or acknowledgement of previous employers).', 'arbeitszeitSchichtNachtWochenende': False, 'arbeitszeitTeilzeitAbend': False, 'arbeitszeitTeilzeitNachmittag': False, 'arbeitszeitTeilzeitVormittag': False, 'arbeitszeitTeilzeitFlexibel': False, 'arbeitszeitVollzeit': True, 'eintrittszeitraum': {'von': '2026-05-05'}, 'verguetungsangabe': 'KEINE_ANGABEN', 'vertragsdauer': 'BEFRISTET', 'befristetBis': '2029-09-30', 'istGeringfuegigeBeschaeftigung': False, 'istBehinderungGefordert': False, 'stellenlokationen': [{'adresse': {'strasse': 'Am Schwarzenberg-Campus 1', 'plz': '21073', 'ort': 'Hamburg', 'region': 'HAMBURG', 'land': 'DEUTSCHLAND'}, 'breite': 53.463591, 'laenge': 9.9697185}], 'homeofficemoeglich': False, 'istPrivateArbeitsvermittlung': False, 'istArbeitnehmerUeberlassung': False, 'veroeffentlichungszeitraum': {'von': '2026-04-27'}, 'datumErsteVeroeffentlichung': '2026-04-27', 'aenderungsdatum': '2026-05-05T10:05:29.267', 'istBetreut': True, 'hauptberuf': 'Wissenschaftliche/r Mitarbeiter/in', 'firma': 'Technische Universität Hamburg', 'arbeitgeberKundennummerHash': 'vTis17PTUFvwW4EKGaJL_3ks_4I8E2m2o2UZhYxtx4Q=', 'allianzpartnerUrl': 'www.tuhh.de', 'allianzpartnerName': 'Technische Universität Hamburg', 'referenznummer': '20536-lutif851vc-S'}

In [37]:
meine_gold.loc[i, "homeoffice"] = fabio_gold.loc[i, "homeoffice"]
meine_gold.loc[i, "vertragsart"] = fabio_gold.loc[i, "vertragsart"]
meine_gold.loc[i, "erfahrungslevel"] = fabio_gold.loc[i, "erfahrungslevel"]
meine_gold.loc[i, "gehalt_min_eur"] = fabio_gold.loc[i, "gehalt_min_eur"]
meine_gold.loc[i, "gehalt_zeitraum"] = fabio_gold.loc[i, "gehalt_zeitraum"]
meine_gold.loc[i, "skills_top3"] = fabio_gold.loc[i, "skills_top3"]
meine_gold.loc[i, "notiz"] = fabio_gold.loc[i, "notiz"]

meine_gold

,id,homeoffice,vertragsart,erfahrungslevel,gehalt_min_eur,gehalt_zeitraum,skills_top3,notiz
0,15939-BB-633097-7878-9999-S,ja,festanstellung,junior,nicht_genannt,nicht_genannt,FMECA|Reliability Block Diagrams|ILS,"Junior entschieden ohne expliziete Nennung, du..."
1,15939-BB-633095-7878-7490-S,ja,festanstellung,senior,nicht_genannt,nicht_genannt,OPUS Suite|Python,
2,15939-BB-633455-7878-6343-S,nicht_genannt,festanstellung,senior,nicht_genannt,nicht_genannt,Data-Lake-/Lakehouse-Architektur|Data-Ingestio...,"festanstellung anhand 30 Tage Urlaub, senior a..."
3,15939-BB-633457-7878-2175-S,nicht_genannt,festanstellung,senior,nicht_genannt,nicht_genannt,MLOps|Platform Engineering|Model Deployment,festanstellung anhand von 30 Tage Urlaub
4,18777-931781141-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,13999-k53401.30280-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,15939-BB-632493-7878-9058-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,13635-7fbe73ac_JB5131141-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20536-lutif851vc-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,12826-SA0136034_JB5125696-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,13509-00002110865001-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12862-244829-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
#meine_gold.loc[i, "homeoffice"] = "ja"
#meine_gold.loc[i, "vertragsart"] = "festanstellung"
#meine_gold.loc[i, "erfahrungslevel"] = "junior"
#meine_gold.loc[i, "gehalt_min_eur"] = "nicht_genannt"
#meine_gold.loc[i, "gehalt_zeitraum"] = "nicht_genannt"
#meine_gold.loc[i, "skills_top3"] = "python|opus suite|datenanalyse"
meine_gold.loc[i, "notiz"] = "unbefristet -> festanstellung"

meine_gold

,id,homeoffice,vertragsart,erfahrungslevel,gehalt_min_eur,gehalt_zeitraum,skills_top3,notiz
0,15939-BB-633097-7878-9999-S,ja,festanstellung,junior,nicht_genannt,nicht_genannt,FMECA|Reliability Block Diagrams|ILS,"Junior entschieden ohne expliziete Nennung, du..."
1,15939-BB-633095-7878-7490-S,ja,festanstellung,senior,nicht_genannt,nicht_genannt,OPUS Suite|Python,
2,15939-BB-633455-7878-6343-S,nicht_genannt,festanstellung,senior,nicht_genannt,nicht_genannt,Data-Lake-/Lakehouse-Architektur|Data-Ingestio...,"festanstellung anhand 30 Tage Urlaub, senior a..."
3,15939-BB-633457-7878-2175-S,nicht_genannt,festanstellung,senior,nicht_genannt,nicht_genannt,MLOps|Platform Engineering|Model Deployment,festanstellung anhand von 30 Tage Urlaub
4,18777-931781141-S,nicht_genannt,festanstellung,nicht_genannt,nicht_genannt,nicht_genannt,Siemens Polarion|IBM Rational DOORS|systems en...,unbefristet -> festanstellung
5,13999-k53401.30280-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,15939-BB-632493-7878-9058-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,13635-7fbe73ac_JB5131141-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20536-lutif851vc-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,12826-SA0136034_JB5125696-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,13509-00002110865001-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12862-244829-S,NaN,NaN,NaN,NaN,NaN,NaN,NaN